/*
 * This file is part of ludo. See the LICENSE file for the full license governing this code.
 */

#include <GLFW/glfw3.h>

#include "input.h"

namespace ludo
{
  std::unordered_map<int, keyboard_button> input_map =
  {
    { GLFW_KEY_0, keyboard_button_zero },
    { GLFW_KEY_1, keyboard_button_one },
    { GLFW_KEY_2, keyboard_button_two },
    { GLFW_KEY_3, keyboard_button_three },
    { GLFW_KEY_4, keyboard_button_four },
    { GLFW_KEY_5, keyboard_button_five },
    { GLFW_KEY_6, keyboard_button_six },
    { GLFW_KEY_7, keyboard_button_seven },
    { GLFW_KEY_8, keyboard_button_eight },
    { GLFW_KEY_9, keyboard_button_nine },
    { GLFW_KEY_A, keyboard_button_a },
    { GLFW_KEY_B, keyboard_button_b },
    { GLFW_KEY_C, keyboard_button_c },
    { GLFW_KEY_D, keyboard_button_d },
    { GLFW_KEY_E, keyboard_button_e },
    { GLFW_KEY_F, keyboard_button_f },
    { GLFW_KEY_G, keyboard_button_g },
    { GLFW_KEY_H, keyboard_button_h },
    { GLFW_KEY_I, keyboard_button_i },
    { GLFW_KEY_J, keyboard_button_j },
    { GLFW_KEY_K, keyboard_button_k },
    { GLFW_KEY_L, keyboard_button_l },
    { GLFW_KEY_M, keyboard_button_m },
    { GLFW_KEY_N, keyboard_button_n },
    { GLFW_KEY_O, keyboard_button_o },
    { GLFW_KEY_P, keyboard_button_p },
    { GLFW_KEY_Q, keyboard_button_q },
    { GLFW_KEY_R, keyboard_button_r },
    { GLFW_KEY_S, keyboard_button_s },
    { GLFW_KEY_T, keyboard_button_t },
    { GLFW_KEY_U, keyboard_button_u },
    { GLFW_KEY_V, keyboard_button_v },
    { GLFW_KEY_W, keyboard_button_w },
    { GLFW_KEY_X, keyboard_button_x },
    { GLFW_KEY_Y, keyboard_button_y },
    { GLFW_KEY_Z, keyboard_button_z },
    { GLFW_KEY_F1, keyboard_button_f1 },
    { GLFW_KEY_F2, keyboard_button_f2 },
    { GLFW_KEY_F3, keyboard_button_f3 },
    { GLFW_KEY_F4, keyboard_button_f4 },
    { GLFW_KEY_F5, keyboard_button_f5 },
    { GLFW_KEY_F6, keyboard_button_f6 },
    { GLFW_KEY_F7, keyboard_button_f7 },
    { GLFW_KEY_F8, keyboard_button_f8 },
    { GLFW_KEY_F9, keyboard_button_f9 },
    { GLFW_KEY_F10, keyboard_button_f10 },
    { GLFW_KEY_F11, keyboard_button_f11 },
    { GLFW_KEY_F12, keyboard_button_f12 },

    { GLFW_KEY_APOSTROPHE, keyboard_button_apostrophe },
    { GLFW_KEY_BACKSLASH, keyboard_button_backslash },
    { GLFW_KEY_BACKSPACE, keyboard_button_backspace },
    { GLFW_KEY_COMMA, keyboard_button_comma },
    { GLFW_KEY_DELETE, keyboard_button_del },
    { GLFW_KEY_ESCAPE, keyboard_button_escape },
    { GLFW_KEY_EQUAL, keyboard_button_equals },
    { GLFW_KEY_GRAVE_ACCENT, keyboard_button_grave },
    { GLFW_KEY_LEFT_BRACKET, keyboard_button_left_bracket },
    { GLFW_KEY_MINUS, keyboard_button_minus },
    { GLFW_KEY_PERIOD, keyboard_button_period },
    { GLFW_KEY_ENTER, keyboard_button_enter },
    { GLFW_KEY_RIGHT_BRACKET, keyboard_button_right_bracket },
    { GLFW_KEY_SEMICOLON, keyboard_button_colon },
    { GLFW_KEY_SLASH, keyboard_button_slash },
    { GLFW_KEY_SPACE, keyboard_button_space },
    { GLFW_KEY_TAB, keyboard_button_tab },
    { GLFW_KEY_DOWN, keyboard_button_arrow_down },
    { GLFW_KEY_LEFT, keyboard_button_arrow_left },
    { GLFW_KEY_RIGHT, keyboard_button_arrow_right },
    { GLFW_KEY_UP, keyboard_button_arrow_up },
    { GLFW_KEY_DELETE, keyboard_button_del },
    { GLFW_KEY_END, keyboard_button_end },
    { GLFW_KEY_HOME, keyboard_button_home },
    { GLFW_KEY_INSERT, keyboard_button_insert },
    { GLFW_KEY_LEFT_ALT, keyboard_button_left_alt },
    { GLFW_KEY_LEFT_CONTROL, keyboard_button_left_ctrl },
    { GLFW_KEY_LEFT_SHIFT, keyboard_button_left_shift },
    { GLFW_KEY_PAGE_DOWN, keyboard_button_page_down },
    { GLFW_KEY_PAGE_UP, keyboard_button_page_up },
    { GLFW_KEY_RIGHT_ALT, keyboard_button_right_alt },
    { GLFW_KEY_RIGHT_CONTROL, keyboard_button_right_ctrl },
    { GLFW_KEY_RIGHT_SHIFT, keyboard_button_right_shift }
  };
}
